-- H2 2.1.214; 
SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS "SA" SALT 'bb38af8fed566570' HASH '21b7a0b7822e49c228946e75eda19d36c360fca82e91726ea7d82a657a249d38' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."furniture_application$furniture"(
    "PRICE" INTEGER NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "NAME" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."furniture_application$furniture" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");               
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."furniture_application$furniture";        
INSERT INTO "PUBLIC"."furniture_application$furniture" VALUES
(500, 1, 'Sofa');
CREATE MEMORY TABLE "PUBLIC"."NIGGER"(
    "I" INTEGER
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.NIGGER;   
