#!/bin/bash

# Flip kerner ipv6 enabled status

fgrep 0 /proc/sys/net/ipv6/conf/all/disable_ipv6 &> /dev/null

if [ $? == "0" ]; then
	sudo sh -c 'echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
	echo "IPv6 connections are now disabled."
	else
	sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
	echo "IPv6 connections are now enabled."
fi
