/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void new_exc() {
        var e = new AutomaticDoorException(
            AutomaticDoorException.DoorErrorType.ALREADY_IN_STATE
        );
        assertEquals(e.errno, AutomaticDoorException.DoorErrorType.ALREADY_IN_STATE);
    }

    @Test
    void new_door() {
        var d = new AutomaticDoorFakeCorp8001();
    }

    @Test
    void new_double_close() {
        var d = new AutomaticDoorFakeCorp8001();
        try {
            d.close();
            d.close();
        } catch (AutomaticDoorException e) {
            assertEquals(e.errno, AutomaticDoorException.DoorErrorType.ALREADY_IN_STATE);
        }
    }

    @Test
    void new_double_open() {
        var d = new AutomaticDoorFakeCorp8001();
        try {
            d.open();
            d.open();
        } catch (AutomaticDoorException e) {
            assertEquals(e.errno, AutomaticDoorException.DoorErrorType.ALREADY_IN_STATE);
        }
    }

    @Test
    void new_lift() {
        var d = new AutomaticDoorFakeCorp8001();
        var l = new Lift(10, d);
    }

    @Test
    void lift_do_something() {
        var d = new AutomaticDoorFakeCorp8001();
        var l = new Lift(10, d);
        l.move_up();
    }

    @Test
    void lift_calls_jani() {
        var d = new MockStickyAutomaticDoor();
        var l = new Lift(10, d);
        l.move_up();
        assertEquals(l.was_jani_called, true);
    }
}
