server.modules = (
    "mod_cgi",
    "mod_alias",
    "mod_setenv"
)

server.document-root = "/home/anon/gorillanest/"
server.port = 5050

alias.url += ( "/git" => "PATH/cgi/git-http-backend" )

$HTTP["url"] =~ "^/git" {
	cgi.assign = ("" => "")
	setenv.add-environment = (
		"GIT_PROJECT_ROOT" => "/home/anon/gorillanest/repositories/",
		"GIT_HTTP_EXPORT_ALL" => "1"
	)
}

server.errorlog = "lighttpd-error.log"
